FROM node:20-alpine AS deps

WORKDIR /app

COPY web/package.json web/yarn.lock ./
RUN npm install

FROM node:20-alpine AS builder

WORKDIR /app

ARG NEXT_PUBLIC_QA_API_URL=http://localhost:8000/api/qa
ARG NEXT_PUBLIC_QA_API_KEY=
ENV NEXT_PUBLIC_QA_API_URL=$NEXT_PUBLIC_QA_API_URL
ENV NEXT_PUBLIC_QA_API_KEY=$NEXT_PUBLIC_QA_API_KEY
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY web/ ./

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_QA_API_URL=http://localhost:8000/api/qa
ARG NEXT_PUBLIC_QA_API_KEY=
ENV NEXT_PUBLIC_QA_API_URL=$NEXT_PUBLIC_QA_API_URL
ENV NEXT_PUBLIC_QA_API_KEY=$NEXT_PUBLIC_QA_API_KEY

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "run", "start", "--", "-p", "3000"]